config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :orders
      resources :users
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
    validates :device_model, :imei, :anual_price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    validates :cpf, presence: true
    validates_uniqueness_of :cpf
end

app/controllers/api/v1/orders_controller.rb
class Api::V1::OrdersController < ApplicationController
  before_action :set_order, only: [:show, :update, :destroy]

  # GET /orders
  def index
   @orders = Order.all
   render json: @orders
  end

  # GET /orders/1
  def show
   render json: @order
  end

  # POST /orders
  def create
   @order = Order.new(order_params)
   if @order.save
    render json: @order, status: :created, location:        api_v1_order_url(@order)
   else
    render json: @order.errors, status: :unprocessable_entity
   end
  end

  # PATCH/PUT /orders/1
  def update
   if @order.update(order_params)
    render json: @order
   else
    render json: @order.errors, status: :unprocessable_entity
   end
  end

 # DELETE /orders/1
  def destroy
    if @order.destroy
      render json: { status:true }, status: :ok
    else
      render json: { status:false }, status: :error
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_order
   @order = Order.find(params[:id])
  end
  
  # Only allow a trusted parameter “white list” through.
  def order_params
  params.require(:order).permit(:device_model, :imei, :anual_price, :installments)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  before_action :set_user, only: [:show, :update, :destroy]

  # GET /users
  def index
   @users = User.all
   render json: @users
  end

  # GET /users/1
  def show
   render json: @user
  end

  # POST /users
  def create
   @user = User.new(user_params)
   if @user.save
    render json: @user, status: :created, location:        api_v1_user_url(@user)
   else
    render json: @user.errors, status: :unprocessable_entity
   end
  end

  # PATCH/PUT /users/1
  def update
   if @user.update(user_params)
    render json: @user
   else
    render json: @user.errors, status: :unprocessable_entity
   end
  end

 # DELETE /users/1
  def destroy
    if @user.destroy
      render json: { status:true }, status: :ok
    else
      render json: { status:false }, status: :error
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
   @user = User.find(params[:id])
  end

  # Only allow a trusted parameter “white list” through.
  def user_params
    params.require(:user).permit(:name, :email, :cpf)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PitziApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :device_model %>
    <%= form.text_field :device_model %>
  </div>

  <div class="field">
    <%= form.label :imei %>
    <%= form.text_field :imei %>
  </div>

  <div class="field">
    <%= form.label :anual_price %>
    <%= form.text_field :anual_price %>
  </div>

  <div class="field">
    <%= form.label :installments %>
    <%= form.number_field :installments %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Device model</th>
      <th>Imei</th>
      <th>Anual price</th>
      <th>Installments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.device_model %></td>
        <td><%= order.imei %></td>
        <td><%= order.anual_price %></td>
        <td><%= order.installments %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Device model:</strong>
  <%= @order.device_model %>
</p>

<p>
  <strong>Imei:</strong>
  <%= @order.imei %>
</p>

<p>
  <strong>Anual price:</strong>
  <%= @order.anual_price %>
</p>

<p>
  <strong>Installments:</strong>
  <%= @order.installments %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Cpf</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.cpf %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @user.cpf %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>